# Generated by Django 6.0.2 on 2026-02-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_interestoption_remove_user_interests_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestoption',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
