from django.urls import path

from .views import (
    ForgotPasswordEmailView,
    ForgotPasswordResetView,
    ForgotPasswordVerifyCodeView,
    InterestOptionListView,
    LoginView,
    LogoutView,
    ProfileView,
    ResetPasswordView,
    RegisterCompleteView,
    RegisterEmailView,
    RegisterSetPasswordView,
    RegisterVerifyCodeView,
)

urlpatterns = [
    path("interests", InterestOptionListView.as_view()),
    path("interests/", InterestOptionListView.as_view()),
    path("register/email", RegisterEmailView.as_view()),
    path("register/email/", RegisterEmailView.as_view()),
    path("register/verify", RegisterVerifyCodeView.as_view()),
    path("register/verify/", RegisterVerifyCodeView.as_view()),
    path("register/password", RegisterSetPasswordView.as_view()),
    path("register/password/", RegisterSetPasswordView.as_view()),
    path("register/complete", RegisterCompleteView.as_view()),
    path("register/complete/", RegisterCompleteView.as_view()),
    path("login", LoginView.as_view()),
    path("login/", LoginView.as_view()),
    path("logout", LogoutView.as_view()),
    path("logout/", LogoutView.as_view()),
    path("profile", ProfileView.as_view()),
    path("profile/", ProfileView.as_view()),
    path("password/reset", ResetPasswordView.as_view()),
    path("password/reset/", ResetPasswordView.as_view()),
    path("password/forgot/email", ForgotPasswordEmailView.as_view()),
    path("password/forgot/email/", ForgotPasswordEmailView.as_view()),
    path("password/forgot/verify", ForgotPasswordVerifyCodeView.as_view()),
    path("password/forgot/verify/", ForgotPasswordVerifyCodeView.as_view()),
    path("password/forgot/reset", ForgotPasswordResetView.as_view()),
    path("password/forgot/reset/", ForgotPasswordResetView.as_view()),
]
