# Generated by Django 6.0.2 on 2026-02-27 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AI', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aievaluation',
            name='chat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='chat.chatsession'),
        ),
        migrations.AddField(
            model_name='aitask',
            name='chat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_task', to='chat.chatsession'),
        ),
        migrations.AddField(
            model_name='submission',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='chat.chatsession'),
        ),
    ]
